# Generated by Django 6.1.1 on 2026-10-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_alter_foldermember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldermember',
            name='approve_uploads',
            field=models.CharField(choices=[('none', 'No approval'), ('first', 'First upload only'), ('every', 'Every upload')], default='none', max_length=6),
        ),
        migrations.AddField(
            model_name='foldermember',
            name='first_upload_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foldermember',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foldermember',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foldermember',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='foldermember',
            name='otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foldermember',
            name='otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foldermember',
            name='require_otp',
            field=models.BooleanField(default=False),
        ),
    ]
