# Generated by Django 6.1.1 on 2026-10-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0003_member_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldermember',
            name='otp_channel',
            field=models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=10),
        ),
    ]
