# Generated by Django 6.1.1 on 2026-10-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0004_foldermember_otp_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldermember',
            name='delete_scope',
            field=models.CharField(choices=[('own', 'Only files they sent'), ('all', 'Any file')], default='own', max_length=4),
        ),
    ]
