# Generated by Django 5.2.1 on 2026-10-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0005_delete_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldermember',
            name='approve_uploads',
            field=models.CharField(choices=[('none', 'No approval'), ('first', 'First upload only'), ('every', 'Every upload')], db_default='none', default='none', max_length=6),
        ),
        migrations.AlterField(
            model_name='foldermember',
            name='delete_scope',
            field=models.CharField(choices=[('own', 'Only files they sent'), ('all', 'Any file')], db_default='own', default='own', max_length=4),
        ),
        migrations.AlterField(
            model_name='foldermember',
            name='first_upload_approved',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='foldermember',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='foldermember',
            name='otp_channel',
            field=models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], db_default='email', default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='foldermember',
            name='require_otp',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
