# Generated by Django 6.1.1 on 2026-10-06 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0006_member_db_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subshares', to='sharing.folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='subpath',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
