# Generated by Django 6.1.1 on 2026-09-30 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(max_length=64, unique=True)),
                ('job_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('file_name', models.CharField(max_length=255)),
                ('relative_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('direction', models.CharField(default='send', max_length=12)),
                ('share_name', models.CharField(blank=True, max_length=120)),
                ('sender_fp', models.CharField(blank=True, max_length=64)),
                ('receiver_fp', models.CharField(blank=True, max_length=64)),
                ('sender_status', models.CharField(blank=True, max_length=20)),
                ('receiver_status', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('pending', 'Pending'), ('active', 'Active'), ('verifying', 'Verifying'), ('reconnecting', 'Reconnecting'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('speed', models.FloatField(default=0)),
                ('avg_speed', models.FloatField(default=0)),
                ('peak_speed', models.FloatField(default=0)),
                ('connection_type', models.CharField(blank=True, max_length=40)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('folder_id', models.CharField(blank=True, db_index=True, max_length=12)),
                ('job_total', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['sender', '-started_at'], name='transfers_t_sender__b09b1c_idx'), models.Index(fields=['receiver', '-started_at'], name='transfers_t_receive_4538de_idx')],
            },
        ),
    ]
