# Generated by Django 6.1.1 on 2026-10-01 14:22

from django.db import migrations, models


def group_existing(apps, schema_editor):
    """Old rows: give retries of the same file one key and keep only the newest one listed."""
    Rec = apps.get_model("transfers", "TransferRecord")
    newest = {}
    rows = Rec.objects.order_by("pk").values_list("pk", "transfer_id", "sender_id", "job_id", "relative_path",
                                                  "file_name")
    for pk, tid, sender, job, rel, name in rows.iterator():
        key = f"{sender or ''}|{job}|{rel or name}"[:200] if job else tid
        Rec.objects.filter(pk=pk).update(attempt_key=key)
        newest[key] = pk
    Rec.objects.update(superseded=True)
    keep = list(newest.values())
    for i in range(0, len(keep), 500):                       # small batches: SQLite parameter limit
        Rec.objects.filter(pk__in=keep[i:i + 500]).update(superseded=False)


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrecord',
            name='attempt_key',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='superseded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(group_existing, migrations.RunPython.noop),
    ]
