# Generated by Django 6.1.1 on 2026-10-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrecord',
            name='active_last',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='active_seconds',
            field=models.FloatField(default=0),
        ),
    ]
